sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.5
    - php: 5.6


env:
  global:
    - PROJECT_DIR=/testing123/drupal-8.1.0

before_script:


script:

notifications:
  webhooks:
